### PR TITLE
Unused content parameter removed

### LINKED ISSUE #190: VdxCube constructor gets a parameter which is not used
Vdx constructor gets parameter called `content` which is not used, see https://github.com/pytrip/pytrip/blob/v1.2.1/pytrip/vdx.py#L77

```    def __init__(self, content, cube=None):
        self.vois = []
        self.cube = cube
        self.version = "1.2"
```

This leads to buggy usages, like this one: https://github.com/pytrip/pytrip/blob/v1.2.1/pytrip/utils/trip2dicom.py#L62

```
        v = pt.VdxCube(c)
```

Here `c` is assigned to `content` and not to `cube` as intended

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #190

### CODE REVIEW

**Comment by nbassler** [comment]
I hope it wont break pytripgui.

**Comment by nbassler** [comment]
Will also fix #97

**Comment by grzanka** [comment]
I will check pytripgui before making new release

**Comment by grzanka** [comment]
pytripgui also needs to be fixed, see https://github.com/pytrip/pytripgui/blob/83a1081b3b13bc4d9386d4cbc50ccd7dbc28cded/pytripgui/data.py#L167

**Comment by nbassler** [comment]
Closes #196 
Fixes one of the three items in #96

**Pull request merged**
