### PR TITLE
Fix api change, #252

### LINKED ISSUE #252: Missing attribute in tripexecuter.py?
Taking the example from http://pytrip.readthedocs.io/en/stable/examples.html#example-02-trip-execution, I get the following error:

Traceback (most recent call last):
  File "tripplan.py", line 77, in <module>
    my_trip.execute(my_plan)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/tripexecuter/tripexecuter.py", line 132, in execute
    self.ini_execute()
  File "/usr/local/lib/python2.7/dist-packages/pytrip/tripexecuter/tripexecuter.py", line 153, in ini_execute
    self.convert_files_to_voxelplan()
  File "/usr/local/lib/python2.7/dist-packages/pytrip/tripexecuter/tripexecuter.py", line 783, in convert_files_to_voxelplan
    structures.write_to_trip(out_path + ".vdx")
AttributeError: VdxCube instance has no attribute 'write_to_trip'

I have modified only the respective paths to match mine (I want to later do funny things with multiple fields and changed CTs but you have to learn to crawl before you can walk).
TRiP is "installed" locally (added to $PATH).
PyTRiP is 1.3.1.

### PR DESCRIPTION
**Pull request by TokePrintz**
Closes #252

### CODE REVIEW

**Comment by grzanka** [comment]
@TokePrintz can you also fix other places where `write_to_trip` string appears ?
See https://github.com/pytrip/pytrip/search?utf8=%E2%9C%93&q=write_to_trip

**Comment by TokePrintz** [comment]
@grzanka Done!

**Comment by TokePrintz** [comment]
Seems that one test failed?

**Comment by grzanka** [comment]
It is test related to test coverage, you can ignore it.

**Pull request merged**
