### PR TITLE
new interpolator for DDD and other purposes

### LINKED ISSUE #325: can DDD class work with less than three .ddd input files?
https://github.com/pytrip/pytrip/blob/master/pytrip/ddd.py#L135

interpolate.splrep probably requires at least 3 points, otherwise it displays error:
```TypeError: m > k must hold```

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #325 
Partially solving #242

### CODE REVIEW

**Comment by grzanka** [comment]
Slowly getting rid of scipy

**Comment by grzanka** [comment]
@nbassler any comments on that ?

it is a helper class to deal with interpolation (linear based on numpy and spline based on scipy) in a pythonic way.

it still needs a bit more polishing and a bit more documentation, but will solve many annoying issues and will help almost to get rid of scipy

**Comment by nbassler** [comment]
Great, also for the insisting windoze users. 
Are you aware of anything higher than linear interpolation is needed?

**Comment by grzanka** [comment]
There are some places where previously cubic spline interpolation was used (i.e. DDD).
On the other hand numpy offers only 1-D linear interpolation. If we would like to interpolate on energies and on depth in DDD then we need some kind of 2-D interpolation. Here only scipy can help (with 2-D bilinear interpolation and 2-D splines).

Here is the list of pytrip features which require scipy:
 - pytrip/ddd.py (2-D spline or linear interpolation)
 - pytrip/utils/bevlet2oer.py (1-D spline interpolation of HLUT data file)

Here only 1-D linear interpolation is used and numpy is enough:
- pytrip/paths.py

**Comment by nbassler** [comment]
I doubt bevlet2oer involves HLUT. It is just a LET->OER translator. Linear interpolation is sufficient here.

**Comment by grzanka** [comment]
My mistake:
 - HLUT interpolation (linear, not spline) is used in DensityCube class in pytrip/paths.py, see https://github.com/pytrip/pytrip/blob/master/pytrip/paths.py#L245 (BTW - is it another cube and another issue with filenames and extensions?)
 - spline interpolation is used in pytrip/utils/bevlet2oer.py to interpolate LET-OER data. I'd be happy to use linear interpolator also there.

**Comment by nbassler** [comment]
Not sure what the HLUT cube is used for, but I think we should follow the file extensions for those which can be loaded or generated by TRiP only, but maybe also have a generic class (.cub?) for anything else a user may produce. (Like Dose*LET / sqrt(phase of moon) + årotons in LHC))

**Comment by nbassler** [comment]
LET->OER interpolation should be replaced anyway with a real model some time.

**Comment by nbassler** [comment]
@grzanka will this also fix #324 ?

**Comment by grzanka** [comment]
Issue #324 should be solved by PR #339

**Pull request merged**
