### PR TITLE
removed created_by and partially creation_info as TRiP98 is not diges…

### LINKED ISSUE #295: TRiP does not like created_by and creation_info
which is strange, since TST000 is an official plan which has been used earlier with TRiP. Maybe something has changed over the version.

```
TRiP98> bassler@baslup:~/Projects/dasu01$ TRiP98 
--- This is TRiP98-64, Version 1310(compiled May 27 2014 19:45:59), (C) M.Kraemer@gsi.de ---
    @ baslup(Linux #1 SMP Debian 4.9.6-3 (2017-01-28) 4.9.0-1-amd64).
TRiP98> ct "../shieldhit/res/TST000/TST000000" /read

read_hed_file: 
 error = -28 
error in read_hed_file: ../shieldhit/res/TST000/TST000000.hed illegal file structure! 
1999 -28
<E> trpcube.c(Read): read hed file failed
<E> trpct.c(Read): cube read failed
<E> trpct.c(4DRead): cube read failed
<E> trpcmdct.c: cube read failed
```

removing the two tags from .hed will make the file load.

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #295

### CODE REVIEW

**Comment by grzanka** [comment]
Tests failed due to some unneeded import, fixed now.

But I agree that before merging careful tests should be done.

**Comment by nbassler** [comment]
Ok, the original shieldhit/res/TST000 was derived from, had version 1.4 in the header. (See apropos also the very long creation_info text string in that file)

Changing the version string from 1.2 to 1.4 in .hed will make TRiP accept the files with ```creation_info``` and ```created_by```. I think this is a better solution. (Where did that 1.2 come from anyway?)

(Alternatively users can optionally choose a version format.)

**Comment by nbassler** [comment]
I think the issue came up because dcm2trip coverts to 1.2 format. 
When reading these files and then writing again, the extra tags are added, however the version string is not bumped to 1.4.

I think all files trip writes should be version 1.4 (unless user explicitly asks for something else, may be a new low-priority issue)

**Comment by grzanka** [comment]
@nbassler these fields are kept now and saved only if version >= 1.4

**Comment by nbassler** [comment]
could you also make sure, that version is set to 1.4 prior write, even if file read was 1.2?

**Comment by grzanka** [comment]
Nope, file version is kept. But I think this is a separate issue.

**Pull request merged**
