### PR TITLE
reduced LET cube suffix

### LINKED ISSUE #296: LET cubes cannot be read if suffix dot is missing
```
cube_001_subdosemlet.dos
cube_001_subdosemlet.hed
```

trying to read them fails:

```
bassler@baslup:~/Projects/dasu01$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytrip as pt
>>> pt.__version__
'1.3.8'
>>> l = pt.LETCube()
>>> l
<pytrip.let.LETCube object at 0x7fa68b4bae48>
>>> l.read("cube_001_sub")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/.local/lib/python3.5/site-packages/pytrip/cube.py", line 677, in read
    self.read_trip_data_file(path)
  File "/home/bassler/.local/lib/python3.5/site-packages/pytrip/cube.py", line 750, in read_trip_data_file
    raise IOError("Could not find file " + path)
OSError: Could not find file cube_001_sub
>>> l.read("cube_001_subdosemlet")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/.local/lib/python3.5/site-packages/pytrip/cube.py", line 677, in read
    self.read_trip_data_file(path)
  File "/home/bassler/.local/lib/python3.5/site-packages/pytrip/cube.py", line 750, in read_trip_data_file
    raise IOError("Could not find file " + path)
OSError: Could not find file cube_001_subdosemlet
>>> l.read("cube_001_subdosemlet.dos")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/.local/lib/python3.5/site-packages/pytrip/cube.py", line 677, in read
    self.read_trip_data_file(path)
  File "/home/bassler/.local/lib/python3.5/site-packages/pytrip/cube.py", line 743, in read_trip_data_file
    header_file_path = self.discover_file(header_file_name)
  File "/home/bassler/.local/lib/python3.5/site-packages/pytrip/cube.py", line 484, in discover_file
    gzip_file_name = file_name + ".gz"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
>>> 
```

renaming into 
```
cube_001_sub.dosemlet.dos
cube_001_sub.dosemlet.hed
```
works however.

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #296

### CODE REVIEW

**Comment by grzanka** [comment]
Just to test if this would help. Anyway proper error handling needds to be done

**Comment by nbassler** [comment]
Not sure if this improved the situation:

```
>>> l.read("../dasu01/cube_016_sub_2.dosemlet.dos")
>>> l.read("../dasu01/cube_016_sub_2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/Projects/pytrip/pytrip/cube.py", line 716, in read
    self.read_trip_data_file(path)
  File "/home/bassler/Projects/pytrip/pytrip/cube.py", line 804, in read_trip_data_file
    if data_file_path.endswith('.gz'):
AttributeError: 'NoneType' object has no attribute 'endswith'
>>> l.read("../dasu01/cube_016_sub_2.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/Projects/pytrip/pytrip/cube.py", line 716, in read
    self.read_trip_data_file(path)
  File "/home/bassler/Projects/pytrip/pytrip/cube.py", line 800, in read_trip_data_file
    data_file_path = self.discover_file(data_file_name)
  File "/home/bassler/Projects/pytrip/pytrip/cube.py", line 523, in discover_file
    gzip_file_name = file_name + ".gz"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

writing:
```
l.write("cube_016_sub_2")       # <-- makes "cube_016_sub_2dosemlet.dos", but user expects with a dot.
l.write("cube_016_sub_2.dosemlet.dos")   # <--- results in proper file
l.write("cube_016_sub_2.doesmlet.dos")   # <--- (including spelling mistake) leads to cryptic error
>>> l.write("cube_016_sub_2.doesmlet.dos")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/Projects/pytrip/pytrip/let.py", line 50, in write
    self.write_trip_header(header_file)
  File "/home/bassler/Projects/pytrip/pytrip/cube.py", line 359, in write_trip_header
    _fname = os.path.basename(path)
  File "/usr/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

To clarify, from a user perspective I would expect something like this:

LETCube::
- user may specify either basename or full filename
- READING: if only basename is specified, then pytrip will attempt to load either using ```.dosemlet.dos``` or ```dosemlet.dos``` (notice the leading dot)
- READING: if filename is formatted as "foobar.dos" it may still load it, even if "dosemlet" is missing. Philosophy: if user specifies full filename, then the user properly really seriously wants to read this file, and exaclt this file.
- WRITING: if only basename is specified, ```.dosemlet.dos``` will be added.
- WRITING: if full filename (ending with ".dos" only required), then exactly this file name is used, unmodified.

Similarly for DosCube, however note that occasionally ".phys.dos" appears. We may have to worry about this later when we begin to mess around with biological optimization.

**Comment by grzanka** [comment]
Hi, I see your point,

What you propose its doable but goes much beyond my original design where each file was identified with unique and well defined extension.

Until now we have:
 - file extension stored as fields in DosCube, LETCube and other classes
 - parsing located in single place in Cube class: https://github.com/pytrip/pytrip/blob/master/pytrip/cube.py#L539

Now I see that single extension doesn't make sense, seeing i.e. this one:

http://bio.gsi.de/DOCS/TRiP98/PRO/DOCS/trip98cmddose.html
> write
> Writes the current dose cube(s) as specified by file. Naming convention: 
> 
> <file> contains the extension .DOS or .dos: 
> <file> for the physical dose. For the biological dose: <file><xxxx>.DOS and <file><xxxx>.HED, where <xxxx> is "bio", "rbe" and "svv".
> otherwise: 
> <file><xxxx>.dos and <file><xxxx>.hed, where <xxxx> is "phys", "bio", "rbe" or "svv".

I could expand this design by defining following two types of extensions for each class: short required (i.e. '.dos') and long allowed (i.e. '.dosemlet.dos') and properly implement parsing.

We would then have following classes and extensions:

| Class        | Required extensions           | Allowed extensions  |
| ------------- |:-------------:| :-----:|
| DosCube  | .dos + .hed |  [.phys.dos + .phys.hed, .bio.dos + .bio.hed, ...] |
| LETCube  | .dos + .hed  |  .dosemlet.dos + .dosemlet.hed |
| CtxCube  | .ctx + .hed  |   .ctx + .hed |

I need to think about the implementian, but what you propose is doable

**Comment by nbassler** [comment]
Yes, this looks like what we need. Our initial implementation was based on what we knew by then, but the more we use the tool, the wise we get...

Anyway, we should put this on the list for our next hangout meetng.

**Comment by nbassler** [comment]
@grzanka will this one still be needed?

**Comment by grzanka** [comment]
@nbassler no, it could be abondoned

**Comment by nbassler** [comment]
duplicate of #362

**Pull request closed without merging**
