### PR TITLE
porting iterators to python3

### LINKED ISSUE #280: tripexecutor: executing trip does not work with python3
```
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    sys.exit(main(sys.argv[1:]))
  File "main.py", line 76, in main
    plan_simple(c, voi_ptv, dose=3.0, angles=plan_angles)
  File "/home/bassler/Projects/dasu01/trip.py", line 85, in plan_simple
    exe = pte.TripExecuter(ct_images.get_modified_images(plan))
  File "/home/bassler/Projects/pytrip/pytrip/ctimage.py", line 36, in get_modified_images
    for voi in plan.get_vois():
TypeError: iter() returned non-iterator of type 'VoiCollection'
```
this happens several times in the code

can maybe be fixed by e.g.:
substituting
```
for voi in plan.get_vois().vois
```
with 
```
for voi in plan.get_vois().vois
```
but it does not get nicer...

### PR DESCRIPTION
**Pull request by grzanka**
Related to #280

### CODE REVIEW

**Comment by grzanka** [comment]
Following http://stackoverflow.com/questions/29578469/how-to-make-an-object-both-a-python2-and-python3-iterator

@nbassler can you check it ?

**Comment by nbassler** [comment]
goes better, but then this happens:
```
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    sys.exit(main(sys.argv[1:]))
  File "main.py", line 76, in main
    plan_simple(c, voi_ptv, dose=3.0, angles=plan_angles)
  File "/home/bassler/Projects/dasu01/trip.py", line 87, in plan_simple
    exe.execute(plan)
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 134, in execute
    self.execute_simple()
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 161, in execute_simple
    self.run_trip()
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 611, in run_trip
    self.run_trip_local()
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 699, in run_trip_local
    p.stdin.write(self.trip_exec)
TypeError: a bytes-like object is required, not 'str'
```

but that is presumably a new issue?

**Comment by grzanka** [comment]
New issue, but I can fix it in the same PR. This time is string porting

**Comment by grzanka** [comment]
I need to move to other duties. If this PR doesn't fix the problem, feel free to merge and create a new issue. Otherwise I can continue tomorrow around lunchtime (teaching before)

**Comment by nbassler** [comment]
looks better, but another issue remains, will make a new issue.

**Pull request merged**
